[book]
authors = ["Denis Vorkozhokov", "Timofey Ivanov"]
language = "en"
multilingual = false
src = "src"
title = "C++ course notes"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/cpp-kt/cpp-notes"
